apiVersion: v1
kind: Service
metadata:
  name: amazonapi-orders-service
  labels:
    app: amazonapi-orders
spec:
  type: ClusterIP
  selector:
    app: amazonapi-orders
  ports:
    - name: http
      port: 8082
      targetPort: 8082
