services:
  vault:
    image: hashicorp/vault:latest
    container_name: amazon-api-vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_ROOT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
      - ./vault/init-vault.sh:/vault/scripts/init-vault.sh:ro
    command: server -dev -dev-root-token-id=${VAULT_ROOT_TOKEN}
    networks:
      - ci-cd-network
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  jenkins:
    container_name: amazon-api-jenkins
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    depends_on:
      - vault
    network_mode: "host"  # Allow Jenkins to access Minikube on host
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock     # Host Docker (local learning)
      - ~/.kube:/var/jenkins_home/.kube               # So kubectl uses your config
      - ./jenkins/casc.yaml:/var/jenkins_home/casc.yaml
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
      - VAULT_ADDR=http://localhost:8200  # Use localhost since we're on host network
    env_file:
      - .env
    restart: unless-stopped

networks:
  ci-cd-network:
    driver: bridge
