services:
  jenkins:
    container_name: amazon-api-jenkins
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock     # Host Docker (local learning)
      - ~/.kube:/var/jenkins_home/.kube               # So kubectl uses your config
      - ./jenkins/casc.yaml:/var/jenkins_home/casc.yaml
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
    env_file:
      - .env
    restart: unless-stopped
