server:
  port: 8083   # Gateway port (entrypoint)

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        # Route to users-service
        - id: users-service
          uri: http://amazon-api-users-service:8081
          predicates:
            - Path=/users-api/**

        # Route to orders-service
        - id: orders-service
          uri: http://amazonapi-orders-service:8082
          predicates:
            - Path=/api/orders/**

      # (optional) Default filters, etc.
      default-filters:
        - RemoveResponseHeader=Server

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
