apiVersion: v1
kind: Service
metadata:
  name: amazon-api-users-service
  namespace: amazon-api
  labels:
    app: amazon-api-users
spec:
  type: NodePort
  selector:
    app: amazon-api-users
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081   # optional; if omitted, Kubernetes assigns one
