apiVersion: v1
kind: Service
metadata:
  name: amazonapi-orders-service
  namespace: amazon-api
  labels:
    app: amazonapi-orders
spec:
  type: NodePort
  selector:
    app: amazonapi-orders
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      nodePort: 30082   # Different port from users service
