apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secrets
  namespace: amazon-api
type: Opaque
stringData:
  # Jenkins admin credentials
  # Username: admin
  # Password: admin123
  admin-user: admin
  admin-password: admin123
  # Vault root token for dev mode
  vault-root-token: dev-root-token
