apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secrets
  namespace: amazon-api
type: Opaque
stringData:
  # Jenkins admin credentials
  # Username: admin
  # Password: admin123
  admin-user: admin
  admin-password: admin123
  # Vault root token for production mode with persistent storage
  vault-root-token: hvs.qb4jSCwkdHBZwFZw14A7M7qV
