apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: amazon-api

resources:
  - jenkins-configmap.yaml
  - jenkins-secrets.yaml
  - jenkins-pvc.yaml
  - jenkins-rbac.yaml
  - jenkins-deployment.yaml
  - jenkins-service.yaml
