apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: amazon-api

resources:
  - vault-config.yaml
  - vault-configmap.yaml
  - vault-pvc.yaml
  - vault-deployment.yaml
  - vault-service.yaml
