apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-topics-config
  namespace: amazon-api
data:
  topics.json: |
    {
      "topics": [
        {
          "name": "order.created",
          "partitions": 3,
          "replicationFactor": 3,
          "config": {
            "retention.ms": "604800000",
            "segment.ms": "86400000",
            "min.insync.replicas": "2"
          }
        },
        {
          "name": "order.updated",
          "partitions": 3,
          "replicationFactor": 3,
          "config": {
            "retention.ms": "604800000",
            "min.insync.replicas": "2"
          }
        },
        {
          "name": "user.created",
          "partitions": 3,
          "replicationFactor": 3,
          "config": {
            "retention.ms": "604800000",
            "min.insync.replicas": "2"
          }
        },
        {
          "name": "notification.email",
          "partitions": 3,
          "replicationFactor": 3,
          "config": {
            "retention.ms": "259200000",
            "min.insync.replicas": "2"
          }
        }
      ]
    }
