apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kong-prod

commonLabels:
  environment: production

resources:
  - kong-prod-namespace.yaml
  - ../../base

patchesStrategicMerge:
  - kong-prod-patch.yaml
