apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kong-dev

commonLabels:
  environment: development

resources:
  - kong-dev-namespace.yaml
  - ../../base

patchesStrategicMerge:
  - kong-dev-patch.yaml
