apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amazon-api-ingress
  annotations:
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: kong
spec:
  ingressClassName: kong
  rules:
  - host: dev.amazon-api.local
    http:
      paths:
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: amazon-api-users-service
            port:
              number: 8080
      - path: /orders
        pathType: Prefix
        backend:
          service:
            name: amazonapi-orders-service
            port:
              number: 8081
      - path: /notifications
        pathType: Prefix
        backend:
          service:
            name: notifications-service
            port:
              number: 8082
