apiVersion: v1
kind: Service
metadata:
  name: amazon-api-users-service
  labels:
    app: amazon-api-users
spec:
  type: ClusterIP
  selector:
    app: amazon-api-users
  ports:
    - name: http
      port: 8081
      targetPort: 8081
